Neos:
  Neos:
    nodeTypes:
      groups:
        neosrulez_category:
          position: 'end'
          label: 'Category'
    fusion:
      autoInclude:
        NeosRulez.Category: true
    userInterface:
      translation:
        autoInclude:
          NeosRulez.Category:
            - 'NodeTypes/*'
            - 'NodeTypes/Content/*'
            - 'NodeTypes/Document/*'
            - 'NodeTypes/Mixin/*'
            - 'NodeTypes/Mixin/Abstract/*'